name: update-flake
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */8 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
          extra_nix_config: |
            sandbox = false # can't install in act without this
      - uses: cachix/cachix-action@v10
        with:
          name: eh5
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake.lock
        run: nix flake update

      - name: Update packages source info with nvfetcher
        working-directory: ./packages
        run: nix run ..#nvfetcher

      - name: Build develop profile
        run: nix develop --profile dev -c true

      - name: Push store cache to cachix
        if: ${{ !env.ACT }}
        run: cachix push eh5 dev

      - name: Run flake check
        run: nix flake check

      - name: Commit changes
        if: ${{ !env.ACT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update flake"
