name: update-flake
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Update flake.lock
        run: nix flake update

      - name: Run flake check
        run: nix flake check

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update flake.lock
